- hosts: localhost
# modify the variables in common/vars/main.yml
# ntp and dns MUST be set correctly.
  roles:
    - common

  tasks:
  - name: Construct embedded_appliance_vcenter json file
    template:
      src: /root/hxaction/embedded_appliance_vcenter_template.j2
      dest: /root/hxaction/embedded_appliance_vcenter_1.json
    tags: pre-install
  - name: mount VCSA iso to /mnt/vcsa
    mount:
      path: /mnt/vcsa
      src: "{{ vcsa_iso }}"
      fstype: iso9660
      opts: ro,noauto
      state: mounted
    tags: mountiso
  - name: Installing vCenter
    shell: /mnt/vcsa/vcsa-cli-installer/lin64/vcsa-deploy install --accept-eula --no-esx-ssl-verify /root/hxaction/embedded_appliance_vcenter_1.json >> /root/hxaction/vcsa-deploy.log
    tags: install
#  - name: update UCSM HX vmedia policy to ESXI_custom ISO
#  - name: update UCSM boot policy template to boot vmedia
#  - name: boot server
#  - name: update UCSM boot policy template to HDD
  - name: unmount VCSA iso
    mount:
      path: /mnt/vcsa
      src: "{{ vcsa_iso }}"
      fstype: iso9660
      opts: ro,noauto
      state: unmounted
    tags: unmountiso
 
