- hosts: localhost
  connection: local
  tasks:
  - name: update embedded_appliance_vcenter.json
    replace:
      path: /root/hxaction/embedded_appliance_vcenter.json
      regexp: '"{{ item.key }}":.*$'
      replace: '"{{ item.key }}": "{{ item.value }}"'
      backup: yes
    with_dict: "{{ vcenter_entries }}"
    tag: pre-install
  - name: mount VCSA iso to /mnt/vcsa
    mount:
      path: /mnt/vcsa
      src: {{ vcsa_iso }}
      fstype: iso9660
      opts: ro,noauto
      state: present
    tag: pre-install
  - name: Installing vCenter
    shell: /mnt/vcsa/vcsa-cli-install/lin64/vcsa-deploy install --acknowledge-ceip --accept-eula --no-esx-ssl-verify /root/hxaction/embedded_appliance_vcenter.json >> /root/hxaction/vcsa-deploy.log
    tag: install
  - name: update UCSM HX vmedia policy to ESXI_custom ISO
  - name: update UCSM boot policy template to boot vmedia
  - name: boot server
  - 
  
